# Generated by Django 6.0.2 on 2026-02-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto_entrada', models.CharField(max_length=1000)),
                ('fecha', models.DateTimeField(verbose_name='Fecha de publicacion')),
            ],
        ),
    ]
