# Generated by Django 6.0.2 on 2026-02-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='imagen',
            field=models.CharField(default='https://www.shutterstock.com/image-vector/default-ui-image-placeholder-wireframes-600nw-1037719192.jpg', max_length=200),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='texto_entrada',
            field=models.TextField(),
        ),
    ]
