# Generated by Django 6.0.2 on 2026-03-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_entrada_imagen_alter_entrada_texto_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto_noticia', models.TextField()),
                ('fecha', models.DateTimeField(verbose_name='Fecha de publicacion')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias/')),
            ],
        ),
        migrations.DeleteModel(
            name='Entrada',
        ),
    ]
